### ISSUE TITLE
Corrección en articulo

### ISSUE THREAD

**Issue by ggoral** [JoaquinAmatRodrigo/Estadistica-con-R#1]
En el articulo -> "Ejemplo práctico de regresión lineal simple, múltiple, polinomial e interacción entre predictores"

https://rpubs.com/Joaquin_AR/254575

En la sección "Regresión lineal simple" 
donde dice: "Por esta razón los segundos siempre son más amplios que los segundos." 
debería remplazarse por: "Por esta razón los segundos siempre son más amplios que los primeros".

Saludos!

**Comment by JoaquinAmatRodrigo** [comment]
Toda la razón  @ggoral , gracias por comunicarmelo!
